version: '3'

services:
 db:
  image: mysql:5.6
  environment:
   - MYSQL_ROOT_PASSWORD=password
   - MYSQL_DATABASE=db
   - MYSQL_USER=mysite
   - MYSQL_PASSWORD=password
  volumes:
   - ./db:/var/lib/mysql
   - ./db/conf.d:/etc/mysql/conf.d"
  ports:
   - "3306:3306"
 phpmyadmin:
  image: phpmyadmin/phpmyadmin
  ports :
   - "8181:80"
  environment:
   - PMA_USER=root
   - PMA_PASSWORD=password
   - PMA_ARBITRARY=1
  links:
   - db:mysql

volumes:
  db:
   driver: "local"