define({
	"root": {
		"contact_managment_title_label": "Gestion des membres",
		"add_contact_button": "Ajouter un nouveau membre",
		"delete_contact_button": "Supprimer le membre sélectionné",
		"refresh_contact_button": "Rafraichir",
		"contact_grid_civilite_label": "Civilité",
		"contact_grid_nom_label": "Nom",
		"contact_grid_prenom_label": "Prénom",
		"contact_grid_age_label": "Age",
		"contact_panel_information_title": "Information",
		"contact_panel_famille_title": "Famille",
		"contact_panel_activite_title": "Activité(s)",
		"civilite_label": "Civilité",
		"contact_information_empty_contact_info": "Merci de sélectionner un membre",
		"contact_information_nom_label": "Nom",
		"contact_information_nom_placeholder": "",
		"contact_information_prenom_label": "Prénom",
		"contact_information_prenom_placeholder": "",
		"contact_information_date_naissance_label": "Né(e) le",
		"contact_information_date_naissance_placeholder": "",
		"contact_information_telephone_label": "Téléphone",
		"contact_information_telephone_placeholder": "",
		"contact_information_email_label": "Email",
		"contact_information_email_placeholder": "",
		"contact_information_adresse_label": "Adresse",
		"contact_information_adresse_placeholder": "",
		"contact_information_cdp_label": "Code Postal",
		"contact_information_cdp_placeholder": "",
		"contact_information_ville_label": "Ville",
		"contact_information_ville_placeholder": "",
		"contact_information_secu_label": "Sécu",
		"contact_information_secu_placeholder": "",
		"contact_information_employeur_label": "Employeur",
		"contact_information_employeur_placeholder": "",
		"contact_information_lieu_travail_label": "Travail à",
		"contact_information_lieu_travail_placeholder": "",
		"contact_information_telephone_travail_label": "Tel de travail",
		"contact_information_telephone_travail_placeholder": "",
		"contact_information_parent_label": "Parent",
		"contact_information_allocataire_caf_label": "Allocataire CAF",
		"contact_information_allocataire_msa_label": "Allocataire MSA",

		"contact_information_reside_chez_label": "Réside chez",
		"contact_information_certificat_label": "Certificat Médical",
		"contact_information_droit_image_label": "Droit à l'image",
		"contact_information_rentre_seul_label": "Rentre Seul",
		"contact_information_recommendation_label": "Recommendation",
		"contact_information_info_medicale_label":"Informations Médicales",
		"contact_information_save_label":"Sauvegarder les informations",
		"contact_information_reset_label":"Réinitialiser les informations",
		"contact_information_adhesion_label":"Créer une nouvelle adhésion",
		"contact_information_inscription_activite_label":"Inscrire ce contact à une activité",
		"contact_information_inscription_cl_label":"Inscrire cet enfant à un centre de loisir",
		"contact_information_champ_requis_tooltip": "Ce champ est requis",
		"contact_information_erreur_email_tooltip": "Entrer un email valide",
		"contact_information_erreur_tel_tooltip": "Entrer un numéro de téléphone valide",
		"contact_information_erreur_date_tooltip": "Entrer une date valide au format dd/mm/yyyy",
		"contact_information_erreur_time_tooltip": "Entrer un horaire valide au format hh:mm:ss",

		"contact_updated": "Modifications enregistrées avec succès",
		"contact_bad_update_request": "Merci de vérifier les infos ci-dessous",
		"famille_date_inscription_format": "Le dd mmmm yyyy",
		"famille_date_inscription_label": "Date d'inscription",
		"famille_nom_label": "Famille",
		"famille_quartier_label": "Quartier de résidence",
		"famille_caf_label": "Numéro CAF de la famille",
		"famille_caf_quotient_label": "Quotient CAF de la famille",
		"famille_msa_label": "Numéro MSA de la famille",
		"famille_msa_quotient_label": "Quotient MSA de la famille",
		"famille_membre_label": "Membres",
		"famille_avoir_label": "Avoir de la famille",

		// ACTIVITE
		"contact_non_adherent_label": "Ce membre n'est pas adhérent pour cette année",
		"contact_activite_annee_label": "Pour l'année",
		"contact_activite_numero_adherent": "Numéro d'adhérent :",
		"contact_activite_liste_activite_label": "Activité(s) ou le membre est inscrit:",
		"inscription_supprimer_confirmation": "Etes vous sur de vouloir supprimer cette inscription?",
		"delete_inscription_notif_success_title": "Supression d'inscription",
		"delete_inscription_notif_success_text": "Cette inscription a été supprimée avec succès",

		// ADHESION
		"adhesion_erreur_numero_tooltip": "Entrer un numéro valide",
		"adhesion_dialog_title": "Nouvelle Adhésion",
		"adhesion_dialog_nom_label": "Nom",
		"adhesion_dialog_prenom_label": "Prénom",
		"adhesion_dialog_annee_label": "Année d'adhésion",
		"adhesion_dialog_numero_label": "Numéro d'adhérent",
		"adhesion_dialog_tarif_label": "Tarif appliqué",
		"adhesion_dialog_montant_label": "Montant",
		"adhesion_dialog_montant_devise": "€",
		"adhesion_dialog_submit_label": "Créer",
		"adhesion_dialog_annuler_label": "Annuler",
		"adhesion_notif_success_title": "Adhésion",
		"adhesion_notif_success_text": "Adhésion ajouté avec succès.",

		// INSCRIPTION
		"inscription_membre_title": "Ajouter un membre",
		"inscription_membre_famille_label": "Famille",
		"inscription_membre_famille_existante_label": "Famille existante",
		"inscription_membre_adulte_label": "Adulte",
		"inscription_membre_enfant_label": "Enfant",

		"inscription_membre_nom_label": "Nom",
		"inscription_membre_prenom_label": "Prénom",
		"inscription_membre_naissance_label": "Date de naissance",
		"inscription_membre_civilite_label": "Civilité",
		"inscription_membre_annuler_label": "Annuler",
		"inscription_membre_valider_label": "Ajouter",
		"ajout_contact_date_erreur_tooltip": "Entrer une date valide (dd/mm/yyyy)",
		"ajout_contact_requis_tooltip": "Ce champ est requis",
		"inscription_notif_success_title": "Inscription à une activité",
		"inscription_notif_success_text": "Inscription réussie."


	}
});